server:
  port: 8108

spring:
  application:
    name: inube-authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5437/aba
    username : aba
    password: aba
    driver-class-name: org.postgresql.driver
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8106/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthCheck: 
      enabled: true
    instance:
      leaseRenewalIntervalInSeconds: 5
      leaseExpirationDurationInSeconds: 15
      preferIpAddress: true
